import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarPage from "@/components/Navbar";
import FriendDetailsCard from "@/components/FriendDetailsCard";
import FooterPage from "@/components/footer";

import toast, { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >
      <body className="min-h-full max-w-full  mx-auto flex flex-col ">
        <NavbarPage />

       <main className="text-black max-w-10/12 mx-auto  p-4">
         {children}
         {/* <FriendDetailsCard></FriendDetailsCard> */}
         {/* <FriendDetailsPage></FriendDetailsPage> */}
       </main>
<FooterPage></FooterPage>
 <Toaster />
      </body>
    </html>
  );
}
